sudo: required
services:
  - docker
before_install:
  - docker build -t lvl236/react-image -f Dockerfile.dev .
scripts:
  - docker run -e CI=true lvl236/react-image npm run test
deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "react-app-demo"
  env: "Reactappdemo-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-813065799930"
  bucket_path: "react-app-demo"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY